package response

type BaiduAccountInfo struct {
	Userid   int64  `json:"userid"`
	Username string `json:"username"`
	Mccid    int64  `json:"mccid"`
	Fatname  string `json:"fatname"`
	Remark   string `json:"remark"`
}
type BaiduAccountList struct {
	Data []BaiduAccountInfo `json:"data"`
}
type BaiduAccountListResponse struct {
	BaiduHeader          BaiduResponseHeader `json:"header"`
	BaiduAccountListBody BaiduAccountList    `json:"body"`
}
type CostInfo struct {
	Date       string  `json:"date"`
	Hour       int64   `json:"hour"`
	Name       string  `json:"name"`
	Plan       string  `json:"plan"`
	City       string  `json:"city"`
	Impression int64   `json:"impression"`
	Click      int64   `json:"click"`
	Cost       float64 `json:"cost"`
	Product    int     `json:"product"`
}
type BaiduResponseHeader struct {
	Status   int    `json:"status"`  // 0:成功，1:部分失败，2:全部失败，3:系统错误
	Desc     string `json:"desc"`    // 描述
	Rquota   int    `json:"rquota"`  // 剩余的请求配额(现可忽略)
	Quota    int    `json:"quota"`   // 本次请求发送的数据条数
	Oprs     int    `json:"oprs"`    // 成功操作数据条数
	Oprtime  int    `json:"oprtime"` // 操作时间描述
	Traceid  string `json:"traceid"`
	Succ     int    `json:"succ"`
	Failures []struct {
		Code     int    `json:"code"`
		Message  string `json:"message"`
		Position string `json:"position"`
	} `json:"failures"` // 错误信息
}

type BaiduReportResponse struct {
	BaiduReportHeader BaiduResponseHeader     `json:"header"`
	BaiduReportBody   BaiduReportResponseBody `json:"body"`
}

type BaiduReportResponseBody struct {
	Data []struct {
		RowCount      int `json:"rowCount"`
		TotalRowCount int `json:"totalRowCount"`
		Rows          []struct {
			UserName         string  `json:"userName"` //账户名
			Product          int     `json:"product"`  // 投放渠道 0：搜索推广 1：信息流推广 3：阿拉丁推广 4：知识营销
			Date             string  `json:"date"`
			Hour             int64   `json:"hour"`
			Cost             float64 `json:"cost"`
			Impression       int64   `json:"impression"`
			Click            int64   `json:"click"`
			ProvinceCityName string  `json:"provinceCityName"` // 地市 (该指标不支持小时)
			CampaignName     string  `json:"campaignName"`     //计划名称
		} `json:"rows"`
	} `json:"data"`
}

//type AutoGenerated struct {
//	Body struct {
//		Data []struct {
//			RowCount      int `json:"rowCount"`
//			TotalRowCount int `json:"totalRowCount"`
//			Rows          []struct {
//				Date       string  `json:"date"`
//				Cost       float64 `json:"cost"`
//				Impression int     `json:"impression"`
//				UserName   string  `json:"userName"`
//				Click      int     `json:"click"`
//			} `json:"rows"`
//		} `json:"data"`
//	} `json:"body"`
//}
